project_id = "hebhetjvcauitozkxggt"

[functions.generate-mcq]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.admin-notifications]
verify_jwt = false

[functions.youtube-search]
verify_jwt = false

[functions.verify-service-account]
verify_jwt = false

[functions.verify-purchase]
verify_jwt = false

[functions.play-rtdn-webhook]
verify_jwt = false

