import { Link } from "react-router-dom";

export default function Disclaimer() {
  return (
    <main dir="rtl" className="min-h-screen bg-background text-foreground px-5 py-10 max-w-3xl mx-auto leading-relaxed">
      <Link to="/" className="text-sm text-primary underline">← Back to home</Link>
      <h1 className="text-3xl font-bold mt-4 mb-2">Educational Disclaimer</h1>
      <p className="text-sm text-muted-foreground mb-6">Last updated: May 2026</p>

      <div className="bg-destructive/10 border border-destructive/30 rounded-xl p-4 mb-6 text-sm">
        ⚠️ <strong>Important Notice:</strong> This application is intended for{" "}
        <strong>educational and informational purposes only</strong>. It does not provide medical
        diagnosis or treatment. Do not use it as a substitute for professional medical advice.
      </div>

      <section className="space-y-4 text-sm">
        <h2 className="text-xl font-semibold">1. Purpose of the Application</h2>
        <p>
          <strong>Tips &amp; Tricks</strong> is an educational and informational tool designed to help
          those interested in women's health, pregnancy, obstetrics, and reproductive medicine understand
          general concepts, conduct self-review, and prepare for academic examinations such as Prometric
          and MRCOG.
        </p>

        <h2 className="text-xl font-semibold">2. Not Medical Advice</h2>
        <p>
          The information, calculators, and questions presented in the application:
        </p>
        <ul className="list-disc pr-6 space-y-1">
          <li>Do not constitute medical advice or a diagnostic opinion.</li>
          <li>Do not replace clinical examination or laboratory investigations.</li>
          <li>Must not be relied upon for therapeutic decision-making.</li>
          <li>May contain errors or outdated information.</li>
        </ul>

        <h2 className="text-xl font-semibold">3. Informational Calculators</h2>
        <p>
          Calculators (such as estimated delivery date EDD, gestational age, BMI index, and ovulation
          window) provide <strong>approximate results</strong> based on widely used formulae and may
          differ from actual clinical findings. <strong>Always consult a clinician</strong> for an
          accurate assessment.
        </p>

        <h2 className="text-xl font-semibold">4. Questions and Scenarios</h2>
        <p>
          Examination questions and clinical scenarios are drawn from general educational sources and
          published research. They are intended <strong>for academic training only</strong> and are not
          a substitute for official curricula or approved reference textbooks.
        </p>

        <h2 className="text-xl font-semibold">5. AI Assistant (AI Mentor)</h2>
        <p>
          Responses generated by the AI assistant are produced automatically and may contain errors or
          inaccuracies. <strong>Do not use them to make clinical decisions.</strong> Always rely on
          authoritative sources and specialist consultation.
        </p>

        <h2 className="text-xl font-semibold">6. Emergencies</h2>
        <p>
          If you are experiencing bleeding, severe pain, reduced fetal movement, or any emergency
          symptom: <strong>go immediately to the nearest hospital or call emergency services.</strong>{" "}
          Do not use this application in emergency situations.
        </p>

        <h2 className="text-xl font-semibold">7. Limitation of Liability</h2>
        <p>
          The developers, team members, and contributors of this application are{" "}
          <strong>not liable</strong> for any direct or indirect harm — physical, financial, or
          otherwise — arising from:
        </p>
        <ul className="list-disc pr-6 space-y-1">
          <li>The use or misuse of information presented in the application.</li>
          <li>Any medical or personal decision made based on the application's content.</li>
          <li>Any error or omission in the content.</li>
        </ul>

        <h2 className="text-xl font-semibold">8. Target Audience</h2>
        <p>
          This application is intended for adults (18+) interested in health knowledge, students in
          health-related faculties, and practitioners who use it exclusively as a{" "}
          <strong>personal review tool</strong>.
        </p>

        <h2 className="text-xl font-semibold">9. Medical Terminology</h2>
        <p>
          The application may contain advanced medical terminology. If you are not a specialist, the
          content may be difficult to understand and could be misinterpreted.{" "}
          <strong>Consult a specialist</strong> to interpret any information.
        </p>

        <h2 className="text-xl font-semibold">10. Acceptance</h2>
        <p>
          By using the application you acknowledge that you have read and understood this disclaimer
          and agree to it in full.
        </p>

        <p className="text-xs text-muted-foreground mt-6">
          See also{" "}
          <Link to="/terms" className="text-primary underline">Terms of Use</Link> and{" "}
          <Link to="/privacy" className="text-primary underline">Privacy Policy</Link>.
        </p>
      </section>
    </main>
  );
}
